
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 10;
  public static final int PLUS = 8;
  public static final int SEMI = 2;
  public static final int CONCAT = 16;
  public static final int FUNCTION = 7;
  public static final int ARG = 4;
  public static final int LBRACKET = 12;
  public static final int RBRACKET = 13;
  public static final int COMMA = 14;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int DIVIDE = 11;
  public static final int LENGTH = 15;
  public static final int MINUS = 9;
  public static final int PRINT = 18;
  public static final int error = 1;
  public static final int LSUB = 20;
  public static final int ASSIGN = 6;
  public static final int DOUBLE_COLON = 3;
  public static final int FSUB = 19;
  public static final int VAR = 5;
  public static final int REVERSE = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "DOUBLE_COLON",
  "ARG",
  "VAR",
  "ASSIGN",
  "FUNCTION",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "LENGTH",
  "CONCAT",
  "REVERSE",
  "PRINT",
  "FSUB",
  "LSUB",
  "NUMBER"
  };
}

